### ISSUE TITLE
tmux-continuum

### ISSUE THREAD

**Issue by alex-popov-tech** [lytedev/dotfiles#5]
Hello! I saw you are using tmux-continuum https://github.com/lytedev/dotfiles/blob/bdda9479e5ad0898c669c50833c9b231fb2544ee/apps/shell/tmux/conf#L114

I am inspired by your dotfiles,  but when i tried to use that plugin, it didn't save sessions on my macos catalina...is it working for you?

**Comment by lytedev** [comment]
Is tmux-resurrect working at all? Have you taken a look at https://github.com/tmux-plugins/tmux-continuum/issues/19 ?

**Comment by lytedev** [comment]
Also, I should note that I don't run macOS, so I probably won't be of too much help. =/

**Comment by alex-popov-tech** [comment]
tmux-ressurect - yes, and now i'm using workaround to automate saving separate window with `watch` command running there...also if i run `continuum-save.sh` manually it also works...

**Comment by alex-popov-tech** [comment]
sorry, i missed the point that you have other OS, i will close that issue, thanks for answering anyways!
